<a href="https://colab.research.google.com/github/sathizz7/Numpy_Task2/blob/main/Copy_of_Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.__version__

'1.21.6'

In [ ]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
X = np.zeros(10)
print(X)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
X.size

10

In [ ]:
X.itemsize

8

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
y = np.zeros(10)

In [ ]:
y[4] = 1

In [ ]:
y

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
A = np.arange(10,50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
A = A[::-1]
print(A)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
B = np.arange(0,9)
B.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
c = [1,2,0,0,4,0]
np.nonzero(c)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
np.random.rand(3,3,3)

array([[[0.59589784, 0.42944161, 0.18972871],
        [0.02369433, 0.61048204, 0.70606912],
        [0.86441503, 0.79785221, 0.35567585]],

       [[0.95232933, 0.80784902, 0.85785598],
        [0.42105955, 0.64839598, 0.54141607],
        [0.58609294, 0.94771254, 0.4574179 ]],

       [[0.83398666, 0.44488006, 0.63670469],
        [0.94585791, 0.71957875, 0.75575806],
        [0.4877922 , 0.78765635, 0.87705883]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
x = np.random.rand(10,10)
print(x)

[[0.88350542 0.07823495 0.49813096 0.9463563  0.39505033 0.48881247
  0.86649404 0.39626522 0.74404775 0.31763579]
 [0.36761807 0.40878359 0.42316048 0.12350478 0.41837358 0.5161031
  0.35066752 0.28142651 0.97789749 0.53487998]
 [0.87265814 0.70065549 0.75865419 0.36527769 0.12444376 0.04112342
  0.84205096 0.52500021 0.21314962 0.81570249]
 [0.71653605 0.3606342  0.8576052  0.53113779 0.80585532 0.54411802
  0.96374887 0.78065929 0.77839655 0.5835528 ]
 [0.74318156 0.68768773 0.7375797  0.52800315 0.97248601 0.12054044
  0.93218141 0.76585782 0.56660243 0.1264133 ]
 [0.06354745 0.77572554 0.32071683 0.20137015 0.04474373 0.46278604
  0.81684909 0.35921137 0.07912645 0.7643231 ]
 [0.05795447 0.7102677  0.74666566 0.5147476  0.89352844 0.11486281
  0.43009847 0.03996072 0.79755119 0.17847177]
 [0.59399869 0.70779068 0.182538   0.29649137 0.17555569 0.16145153
  0.15686951 0.29822761 0.16754332 0.51693758]
 [0.85682413 0.23403916 0.19092304 0.62750433 0.42720041 0.9838479
  0.38059625 0

In [ ]:
x.min()

0.044507206846067016

In [ ]:
x.max()

0.983847897268718

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
y = np.random.rand(30)
y.mean()

0.5166287430134677

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
ones = np.ones(16)
ones = ones.reshape(4,4)

In [ ]:
ones[1:-1, 1:-1] = 0

In [ ]:
print(ones)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
x = np.ones((3,3))

In [ ]:
x = np.pad(x, pad_width= 1, mode = 'constant', constant_values = 0)

In [ ]:
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
nan
False
False
nan
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
np.diag(1 + np.arange(4), k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
a = np.zeros((8, 8), dtype = int)
a[1::2 , ::2] = 1
a[::2 , 1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(100, (6,7,8)))##

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
obj = np.array([[0,1],[1,0]])
np.tile(obj,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x = np.random.rand(5,5)
xmax, xmin = x.max() , x.min()

x = (x - xmin) / (xmax - xmin)
print(x)

[[0.12326844 0.         0.17627162 0.82545074 0.83710597]
 [0.50223375 0.46244491 0.85105522 1.         0.37477902]
 [0.76507035 0.43577701 0.58805342 0.59093558 0.42726428]
 [0.24166493 0.18072681 0.07899513 0.69140397 0.53149565]
 [0.38445002 0.96951331 0.30250211 0.96397899 0.88028449]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([('r', np.ubyte),
                  ('g', np.ubyte),
                  ('b', np.ubyte),
                  ('a', np.ubyte)])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
a = np.arange(10)
arr = (a >=2 ) & (a <= 8)
a[arr] *= -1

In [ ]:
a

array([ 0,  1, -2, -3, -4, -5, -6, -7, -8,  9])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
10
True
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
notlegal
legal
notlegal
legal
legal
notlegal

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan
0
[-9.22337204e+18]

In [ ]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
X = np.array([0,1,2,3,4])
y = np.array([1,3,4])

np.intersect1d(X,y)

array([1, 3, 4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
print('yesterday',np.datetime64('today') - np.timedelta64(1,'D'))

yesterday 2022-11-01


In [ ]:
print('today',np.datetime64('today'))

today 2022-11-02


In [ ]:
print('tommrow',np.datetime64('today') + np.timedelta64(1,'D'))

tommrow 2022-11-03


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
print(np.arange('2016-06', '2016-07', dtype = 'datetime64[D]'))

['2016-06-01' '2016-06-02' '2016-06-03' '2016-06-04' '2016-06-05'
 '2016-06-06' '2016-06-07' '2016-06-08' '2016-06-09' '2016-06-10'
 '2016-06-11' '2016-06-12' '2016-06-13' '2016-06-14' '2016-06-15'
 '2016-06-16' '2016-06-17' '2016-06-18' '2016-06-19' '2016-06-20'
 '2016-06-21' '2016-06-22' '2016-06-23' '2016-06-24' '2016-06-25'
 '2016-06-26' '2016-06-27' '2016-06-28' '2016-06-29' '2016-06-30']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)
B = np.ones(3)*2

np.add(A,B,out = B)
np.divide(A,2,out = A)
np.negative(A , out = A)
np.multiply(A, B , out = A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
n = np.random.uniform(0,15,10)
print(n)

print(np.floor(n))

[14.73100063  3.42709449 13.10137162 12.67339331  8.13093386  4.96890264
  5.25833877  7.88362354 12.83597608 10.88836407]
[14.  3. 13. 12.  8.  4.  5.  7. 12. 10.]


In [ ]:
print(np.ceil(n))

[15.  4. 14. 13.  9.  5.  6.  8. 13. 11.]


In [ ]:
n.astype(int)

array([14,  3, 13, 12,  8,  4,  5,  7, 12, 10])

In [ ]:
np.trunc(n)

array([14.,  3., 13., 12.,  8.,  4.,  5.,  7., 12., 10.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
n= np.zeros((5,5))
n += np.arange(5)
print(n)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def gen():
  for n in range(11):
    yield n
nums = np.fromiter(gen(), dtype = float)
print(nums)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
n = np.random.rand(1,10)
print(n)

[[0.70585866 0.74770629 0.02969538 0.28081266 0.59507386 0.83086612
  0.91264167 0.07342701 0.5538842  0.26345761]]


In [ ]:
np.sort(n)

array([[0.02969538, 0.07342701, 0.26345761, 0.28081266, 0.5538842 ,
        0.59507386, 0.70585866, 0.74770629, 0.83086612, 0.91264167]])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
n = np.ones(10)
np.add.reduce(n, dtype = int)

10

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
a = np.ones(10)
b = np.ones(10)

np.array_equal(a,b)

True

In [ ]:
np.allclose(a,b)

True

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
n = np.ones(10)
n.flags.writeable

True

In [ ]:
n.dtype

dtype('float64')

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
n = np.random.random((10,2))
x,y = n[:,0] , n[:,1]

r = np.sqrt(x**2 + y**2)
s = np.arctan2(y, x)

print(r)
print(s)

[0.96317502 0.0866361  0.86468708 1.02960213 0.79495259 0.15016197
 1.06609246 0.51405545 1.13846542 0.99405275]
[0.81502545 0.74254737 0.67463065 0.63153014 1.41643212 0.6514335
 0.6782569  0.81966249 0.52196788 1.12477094]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
n = np.random.random(10)
n[n.argmax()] = 0

print(n)

[0.45720084 0.30522629 0.80798205 0.87023692 0.3527855  0.
 0.52335933 0.18210927 0.68922013 0.0443369 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
Z = np.zeros((5,5), [('x', float),('y', float)])
Z['x'] , Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
x = np.ones(10)
y = x* 0.5

x = x.reshape(-1, 1)

z = x - y

z = 1 / z
print('cauchy matrix',z)

cauchy matrix [[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:

  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [ ]:
for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold = float('inf'))

n = np.zeros((40,40))
print(n)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
z = np.arange(100)
v = np.random.uniform(0,100)

index = (np.abs(z - v)).argmin()
print(index)

5


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


In [ ]:
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
Z = np.random.random((100,2))

x, y = np.atleast_2d(Z[:,0], Z[:, 1])
d = np.sqrt((x - x.T)**2 + (y - y.T)**2)
print(d)

[[0.         0.5003364  0.48434696 0.51049714 0.28913818 0.4477541
  0.28901209 0.59714942 0.79314652 0.72372308 0.64211895 0.32233052
  0.51565615 0.94139901 0.71657536 0.64179242 0.26766388 0.28538023
  0.93309709 0.88746432 0.61078305 0.7712784  0.24829998 0.36058117
  0.43834531 0.08928701 0.62293038 0.80672548 0.31988578 0.74279883
  0.36105684 0.43578529 0.88097889 0.57155249 0.43246042 0.54714907
  0.62162636 0.59863291 0.58221529 0.83304649 0.50375033 0.71985484
  0.77013945 0.56200747 0.41980154 0.70057821 0.69672528 0.26992719
  0.95158998 0.33966859 0.74237669 0.93335969 0.61711295 0.3885264
  0.45038974 0.64438209 0.1911929  0.1676286  0.66624893 0.27122336
  0.31948286 0.46714256 0.78285858 0.54564365 0.93867485 1.03067207
  0.19124286 0.64526788 0.17521308 0.80659282 0.3875752  1.06889925
  0.471618   0.78642906 0.15225759 0.44006504 0.78138962 0.17948468
  0.63077831 0.80571961 0.92876122 0.65097096 0.7104463  0.72482372
  0.80478909 0.14736453 0.44194624 0.01859755 0.10

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
n = (np.random.rand(10)* 100).astype(np.float32)           ####
m = n.view(np.int32)

m[:] = n

print(m)

[68 11 98 20 21 85 67 25 17 85]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11''')

Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
  print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [ ]:
for index in np.ndindex(Z.shape):
  print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [ ]:
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
x, y =  np.meshgrid(np.linspace(-5,5,20), np.linspace(-5,5,10))

sqr = np.sqrt(x*x + y*y)
sigma, mean = 1.0 , 0.0 
res = np.exp( -(sqr - mean)**2 / 2.0 * sigma **2)

In [ ]:
res

array([[1.38879439e-11, 1.68022165e-10, 1.54096233e-09, 1.07130785e-08,
        5.64590245e-08, 2.25553345e-07, 6.83064941e-07, 1.56809199e-06,
        2.72883890e-06, 3.59982243e-06, 3.59982243e-06, 2.72883890e-06,
        1.56809199e-06, 6.83064941e-07, 2.25553345e-07, 5.64590245e-08,
        1.07130785e-08, 1.54096233e-09, 1.68022165e-10, 1.38879439e-11],
       [1.93776925e-09, 2.34439446e-08, 2.15008748e-07, 1.49478384e-06,
        7.87766445e-06, 3.14712057e-05, 9.53072862e-05, 2.18794119e-04,
        3.80751836e-04, 5.02279192e-04, 5.02279192e-04, 3.80751836e-04,
        2.18794119e-04, 9.53072862e-05, 3.14712057e-05, 7.87766445e-06,
        1.49478384e-06, 2.15008748e-07, 2.34439446e-08, 1.93776925e-09],
       [7.86683682e-08, 9.51762889e-07, 8.72879334e-06, 6.06843180e-05,
        3.19812592e-04, 1.27764871e-03, 3.86922678e-03, 8.88246953e-03,
        1.54575296e-02, 2.03912227e-02, 2.03912227e-02, 1.54575296e-02,
        8.88246953e-03, 3.86922678e-03, 1.27764871e-03, 3.1981

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
X = np.arange(15).reshape(5,3)
n = 2
np.put(X,np.random.choice(np.arange(15), n , replace=False),1)

print(X)

[[ 1  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
#type 2
m , n = 7,4
y = np.zeros((m * m), dtype = bool)
np.put(y , np.random.choice(range(m * m),n , replace = False),2)

In [ ]:
y

array([False, False, False, False, False,  True, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False])

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
x = np.random.rand(3,5)
res = x - x.mean(axis = 0)

In [ ]:
res

array([[-0.05106068,  0.08265029,  0.06764842,  0.20603344, -0.07429687],
       [-0.07543947, -0.08342533,  0.08808036, -0.00341918,  0.36866473],
       [ 0.12650015,  0.00077504, -0.15572878, -0.20261426, -0.29436786]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
y = np.random.randint(0,10,(5,3))
#print(y)
print(y[y[:,1].argsort()])

[[2 2 1]
 [2 7 4]
 [3 8 7]
 [8 8 4]
 [1 9 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
n = np.random.randint(0,10,(3,5))
print(~n.any(axis = 0).any())

False


In [ ]:
(~n.all(axis = 0)).any()

False

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
x = np.random.uniform(0,10,15)
v = 4
x.flat[np.abs(x - v).argmin()]

4.443117447781711

In [ ]:
x

array([6.82233218, 0.38765585, 4.44311745, 0.43641154, 7.0168637 ,
       0.51595357, 5.16155373, 9.28718428, 0.66467965, 8.50405072,
       2.78003807, 2.91780176, 2.22297558, 4.84276598, 9.03557828])

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)

i = np.nditer([A,B,None])

for x,y, z in i:z[...] = x + y 
print(i.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
  def __new__(cls, array, name="no name"):
    obj = np.asarray(array).view(cls)
    obj.name = name
    return obj
  def __array_finalize__(self, obj):
    if obj is None: return
    self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
n = np.ones(10)
x = np.random.randint(0,10, 20)
n += np.bincount(x, minlength = len(n))
print(n)

np.add.at(n, x, 1)
print(n)

[3. 2. 2. 2. 4. 2. 4. 5. 2. 4.]
[5. 3. 3. 3. 7. 3. 7. 9. 3. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
x = np.arange(10)
y = np.random.choice(x,(10))

np.bincount(y, x)

array([ 0.,  7., 15.,  4.,  9.,  0.,  5.,  0.,  2.,  3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w, h = 234, 346
img = np.random.randint(0,4,(h,w,3)).astype(np.ubyte)
color = np.unique(img.reshape(-1,3), axis = 0)
n = len(color)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
a = np.arange(60).reshape(2,3,5,2)
print(a.sum(axis = (-2,-1)))

[[ 45 145 245]
 [345 445 545]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)

D_sum = np.bincount(S, weights = D)
D_count = np.bincount(S)

D_mean = D_sum / D_count

In [ ]:
D_mean

array([0.43140447, 0.38253164, 0.55622987, 0.50050353, 0.38315107,
       0.45613576, 0.37017938, 0.44451852, 0.51006563, 0.35387789])

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
a = np.random.rand(1000, 200)
b = np.random.rand(200, 200)

np.diag(np.dot(a,b))

array([50.34056695, 42.21241642, 50.29077351, 48.44245563, 50.66466832,
       49.40182086, 53.72758731, 53.80244497, 50.8773304 , 48.46509729,
       51.19525438, 50.70116051, 57.51139029, 52.33456133, 47.55324877,
       52.47668094, 48.48408781, 48.82323319, 50.84414164, 48.77726117,
       53.65743403, 54.02110841, 48.03695237, 55.42656282, 45.55437018,
       51.26650643, 53.05876233, 52.17738468, 47.62397332, 45.88451054,
       60.26405209, 48.1608371 , 47.73113536, 53.73414167, 48.69117495,
       55.58138206, 46.57445127, 45.83812096, 57.03403062, 54.42647414,
       49.88706164, 50.38173938, 45.59648768, 54.92178155, 54.36515458,
       45.67882804, 45.7539186 , 48.05978327, 48.6920319 , 55.03281954,
       51.92619594, 53.30435139, 50.51279839, 48.16172829, 49.34306581,
       49.16067393, 49.12874745, 50.45919529, 49.96825476, 50.3147743 ,
       53.84089301, 47.13942411, 46.82431816, 44.78475085, 49.58592978,
       47.76986056, 53.60592589, 54.06770337, 54.24576579, 49.18

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
Z = np.array([1,2,3,4,5])
nv = 3

newZ = np.zeros(len(Z) + (len(Z)-1)* (nv))
newZ[::nv + 1] = Z
print(newZ)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
x = np.arange(75).reshape(5,5,3)
y = np.arange(25).reshape(5,5)

In [ ]:
x * y[:,:,None]

array([[[   0,    0,    0],
        [   3,    4,    5],
        [  12,   14,   16],
        [  27,   30,   33],
        [  48,   52,   56]],

       [[  75,   80,   85],
        [ 108,  114,  120],
        [ 147,  154,  161],
        [ 192,  200,  208],
        [ 243,  252,  261]],

       [[ 300,  310,  320],
        [ 363,  374,  385],
        [ 432,  444,  456],
        [ 507,  520,  533],
        [ 588,  602,  616]],

       [[ 675,  690,  705],
        [ 768,  784,  800],
        [ 867,  884,  901],
        [ 972,  990, 1008],
        [1083, 1102, 1121]],

       [[1200, 1220, 1240],
        [1323, 1344, 1365],
        [1452, 1474, 1496],
        [1587, 1610, 1633],
        [1728, 1752, 1776]]])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
n = np.arange(16).reshape(4,4)
n[[0,1]] = n[[1,0]]

In [ ]:
n

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
a = np.random.randint(1,100,(10,3))
b = np.roll(a.repeat(2,axis =1), -1,axis =1)           ####
b = b.reshape(len(b)*3,2)
b = np.sort(b,axis =1)

G = b.view( dtype=[('p0',b.dtype),('p1',b.dtype)] )
G = np.unique(G)
print(G)

[( 1,  7) ( 1, 25) ( 2, 30) ( 2, 59) ( 2, 61) ( 2, 88) ( 3, 24) ( 3, 91)
 ( 7, 25) ( 8, 13) ( 8, 98) (13, 98) (17, 42) (17, 49) (21, 71) (21, 93)
 (24, 91) (25, 28) (25, 61) (28, 61) (30, 59) (42, 49) (48, 73) (48, 88)
 (61, 88) (65, 68) (65, 79) (68, 79) (71, 93) (73, 88)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])

A = np.repeat(np.arange(len(C)), C)

print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def comp_average(a, n=3):
  ret = np.cumsum(a, dtype=float)
  ret[n:] = ret[n:] - ret[:-n]
  return ret[n - 1:] / n
Z = np.arange(20)
print(comp_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks       ####

def rolling(a, window):
  shape = (a.size - window + 1, window)
  strides = (a.strides[0], a.strides[0])
  return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
Z = np.random.randint(0,2,10)
np.logical_not(Z , out = Z)

array([1, 0, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
Y = np.random.uniform(-1.0,1.0, 10 )
np.negative(Y)

array([-0.6181273 , -0.86054625, -0.3888439 , -0.27377523, -0.06145724,
        0.35227031, -0.47217876, -0.20115117,  0.38478691, -0.3203646 ])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(p0,p1,p):
  p0 = np.random.uniform(-10,10,(10,2))
  p1 = np.random.uniform(-10,10,(10,2))
  p = np.random.uniform(-10,10,(1,2))                ####

  T = p1 - p0
  L = (T**2).sum(axis = 1)
  U = -((p0[:,0]-p[...,0])*T[:,0] + (p0[:,1]-p[...,1])*T[:,1]) / L

  U = U.reshape(len(U),1)
  D = p0 + U*T - p
  return np.sqrt((D**2).sum(axis=1))

p0 = np.random.uniform(-10,10,(10,2))
p1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(1,2))

distance(p0,p1,p)

array([ 0.28335836, 10.7646111 ,  7.21847092,  9.76458994,  9.34396829,
       15.2685572 ,  7.34547716,  6.66532386,  5.28710727, 17.97269926])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[11.59270276  0.56980425  4.33166225  2.11680899  0.67572349 13.09721443
   0.98593411  3.67110388  5.97226882 11.09809042]
 [ 2.76422049  6.58279517  3.01949934  0.29045723  5.35322273  2.62596234
   2.62984712  7.77083246  1.3762306   1.82022963]
 [ 5.86324238 11.36605628  1.01835795  0.91142876  0.85919106  1.16289554
  16.10236819 13.3266841   8.64356492  6.87916094]
 [ 7.55322712  0.20066849  2.71034346  8.08878708  5.46842612  3.57673888
   5.23942462  4.22459313  6.95437094 10.29069425]
 [10.57413388  0.86735445 11.46607974  0.18226663  4.78058838  3.28931307
   4.53137195  3.00099402  3.42114577  0.62753425]
 [ 0.08210958  6.38513583  1.10575149  3.95787364  7.59085728 15.21505224
   5.07158378  2.80898866  5.70232826  5.26098418]
 [ 3.102829   14.093385    9.02761049  2.76004815 15.45066207  3.78713055
   1.34600976  0.08197654  8.65282348 11.99077686]
 [ 0.58324036  9.44849149 10.08041817 10.3098895  12.95879842  4.7118883
   6.29991922 12.98403228 10.66158902  6.05587321]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[6 3 2 7 8 6 8 9 6 0]
 [1 1 0 8 6 9 1 2 1 5]
 [4 6 4 0 6 3 5 8 5 1]
 [4 3 2 9 0 4 5 5 7 8]
 [8 1 0 1 3 7 7 3 1 6]
 [8 3 3 8 9 9 8 3 9 1]
 [9 9 8 8 8 3 9 1 0 2]
 [7 1 6 1 7 4 8 3 2 3]
 [4 3 9 7 9 5 3 7 7 0]
 [5 1 6 3 8 0 3 1 9 8]]
[[0 0 0 0 0]
 [0 6 3 2 7]
 [0 1 1 0 8]
 [0 4 6 4 0]
 [0 4 3 2 9]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 4 3]
   [2 1 3]
   [0 3 4]]

  [[4 3 0]
   [1 3 4]
   [3 4 1]]

  [[3 0 4]
   [3 4 4]
   [4 1 2]]

  [[0 4 4]
   [4 4 1]
   [1 2 2]]

  [[4 4 1]
   [4 1 0]
   [2 2 4]]

  [[4 1 1]
   [1 0 1]
   [2 4 3]]

  [[1 1 4]
   [0 1 0]
   [4 3 3]]

  [[1 4 4]
   [1 0 3]
   [3 3 1]]]


 [[[2 1 3]
   [0 3 4]
   [3 4 0]]

  [[1 3 4]
   [3 4 1]
   [4 0 4]]

  [[3 4 4]
   [4 1 2]
   [0 4 2]]

  [[4 4 1]
   [1 2 2]
   [4 2 2]]

  [[4 1 0]
   [2 2 4]
   [2 2 3]]

  [[1 0 1]
   [2 4 3]
   [2 3 0]]

  [[0 1 0]
   [4 3 3]
   [3 0 2]]

  [[1 0 3]
   [3 3 1]
   [0 2 1]]]


 [[[0 3 4]
   [3 4 0]
   [2 4 0]]

  [[3 4 1]
   [4 0 4]
   [4 0 1]]

  [[4 1 2]
   [0 4 2]
   [0 1 1]]

  [[1 2 2]
   [4 2 2]
   [1 1 2]]

  [[2 2 4]
   [2 2 3]
   [1 2 4]]

  [[2 4 3]
   [2 3 0]
   [2 4 2]]

  [[4 3 3]
   [3 0 2]
   [4 2 0]]

  [[3 3 1]
   [0 2 1]
   [2 0 3]]]


 [[[3 4 0]
   [2 4 0]
   [1 1 2]]

  [[4 0 4]
   [4 0 1]
   [1 2 4]]

  [[0 4 2]
   [0 1 1]
   [2 4 1]]

  [[4 2 2]
   [1 1 2]
   [4 1 3]]

  [[2 2 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
  def __setitem__(self, index, value):
    i,j = index
    super(Symetric, self).__setitem__((i,j), value)
    super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
  return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  7  9 10  7]
 [ 7  5 16  5  3]
 [ 9 16  1 42  7]
 [10  5 42  8 12]
 [ 7  3  7 12  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
  N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

  birth = (N==3) & (Z[1:-1,1:-1]==0)
  survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
  Z[...] = 0
  Z[1:-1,1:-1][birth | survive] = 1
  return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
  arrays = [np.asarray(a) for a in arrays]
  shape = (len(x) for x in arrays)

  ix = np.indices(shape, dtype=int)
  ix = ix.reshape(len(arrays), -1).T

  for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

  return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.78 s ± 166 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
151 ms ± 9.99 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
127 ms ± 8.26 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 2 3 4 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 0 0]
 [0 4 4]
 [3 4 2]
 [2 1 2]
 [2 4 1]
 [2 4 3]
 [2 0 1]
 [1 1 3]
 [0 0 1]
 [3 2 3]]
[[0 4 4]
 [3 4 2]
 [2 1 2]
 [2 4 1]
 [2 4 3]
 [2 0 1]
 [1 1 3]
 [0 0 1]
 [3 2 3]]
[[0 4 4]
 [3 4 2]
 [2 1 2]
 [2 4 1]
 [2 4 3]
 [2 0 1]
 [1 1 3]
 [0 0 1]
 [3 2 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 1]]
[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)    
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)   
np.einsum('i,j->ij', A, B)    

array([[0.03135757, 0.19441659, 0.14808233, 0.09387937, 0.02831261,
        0.06097364, 0.0822554 , 0.01101575, 0.03375715, 0.1619534 ],
       [0.14079873, 0.87295057, 0.66490494, 0.42152808, 0.12712654,
        0.27377793, 0.36933525, 0.04946187, 0.15157309, 0.72718751],
       [0.14208464, 0.88092319, 0.67097749, 0.42537788, 0.12828758,
        0.27627833, 0.37270837, 0.04991361, 0.1529574 , 0.73382888],
       [0.07407539, 0.45926662, 0.34981206, 0.22176946, 0.06688234,
        0.14403686, 0.19431037, 0.02602231, 0.07974387, 0.38257945],
       [0.10573937, 0.65558293, 0.49934136, 0.31656617, 0.0954716 ,
        0.2056063 , 0.27736952, 0.0371457 , 0.11383088, 0.54611536],
       [0.07323735, 0.45407077, 0.34585451, 0.2192605 , 0.06612567,
        0.14240732, 0.19211207, 0.02572791, 0.0788417 , 0.37825118],
       [0.06693201, 0.41497769, 0.31607828, 0.20038334, 0.0604326 ,
        0.13014681, 0.17557224, 0.02351287, 0.07205385, 0.34568577],
       [0.08677354, 0.53799497, 0.4097775

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)             
r_int = np.linspace(0, r.max(), 
x_int = np.interp(r_int, r, x)     
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.34766927  0.06817891]
